{
    "name": "GPS Route Sheet",
    "summary": "Route sheets from GPS tracker data",
    "version": "19.0.1.0.0",
    "category": "Fleet",
    "license": "LGPL-3",
    "author": "zhatrus",
    "depends": ["fleet"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/gps_route_sheet_views.xml",
        "views/fleet_vehicle_views.xml",
        "views/res_config_settings_views.xml",
        "views/route_trip_import_wizard_views.xml",
        "report/gps_route_sheet_report.xml",
    ],
    "installable": True,
    "application": False,
}
